POST http://localhost:5000/api/rain
Content-Type: application/json

{
  "count": "1",
  "status": "start"
}

###
POST http://localhost:5000/api/rain
Content-Type: application/json

{
  "count": "30",
  "status": "inProgress"
}

###
POST http://localhost:5000/api/rain
Content-Type: application/json

{
  "count": "30",
  "status": "end"
}

###
DELETE http://localhost:5000/api/car

###
GET http://localhost:5000/api/rain


###
POST http://localhost:5000/api/dht
Content-Type: application/json

{
  "humidity": "86",
  "temperature": "32",
  "createdAt": "10"
}

###
GET http://localhost:5000/api/dht?time=1669540634836&type=date


###
GET http://localhost:5000/api/dht?time=1669454161395&type=month

###
DELETE  http://localhost:3000/api/delete
Content-Type: application/json

{
  "startDay": "2021-11-07 00:00:",
  "endDay": "2021-11-09 00:00:"
}

###
GET http://localhost:5000/api/uv?time=1669454161395&type=month

###
GET http://localhost:5000/api/uv?time=1669540634836&type=date

###
POST http://localhost:5000/api/uv
Content-Type: application/json

{
  "uv": "86",
  "createdAt": "10"
}

###
POST http://localhost:5000/api/sensor
Content-Type: application/json

{
  "status": "1",
  "order": "4"
}

###
GET http://localhost:5000/api/sensor

###
GET http://localhost:5000/api/car

###
POST http://localhost:5000/api/car
Content-Type: application/json

{
  "uid": "2",
  "timeStart": "1669540491112",
  "status": "in"
}

###
POST http://localhost:5000/api/car
Content-Type: application/json

{
  "uid": "1",
  "timeEnd": "1669548061864",
  "status": "out"
}